#!/usr/bin/env node

let fs = require('fs')
let meta = require('./package.json')
let cmd = require('commander')
let cheerio = require('cheerio')

function main() {
    let collect = (val, memo) => { memo.push(val); return memo; }
    cmd.version(meta.version)
        .usage('[options] [file.html]')
	.option('-e, --eval <code>', 'JS')
	.option('-p, --print', 'automatically console.log the result form -e')
	.option('-r, --require <module>', 'preload a module', collect, [])
	.parse(process.argv)

    let src = cmd.args[0] || '/dev/stdin'
    let sandbox = {
	$: parse(src),
	p: console.log.bind(console),
	puts,
    }
    Object.assign(sandbox, preload(cmd.require)) // additional modules

    if (cmd.eval) {
	let r = evaluate(cmd.eval, sandbox)
	if (cmd.print) console.log(r)
    } else {
	if (src === '/dev/stdin') err('repl mode requires a file argument')
	irb(sandbox)
    }
}

function parse(input) {
    try {
	return cheerio.load(fs.readFileSync(input))
    } catch (e) {
	err('failed to load html:', e.message)
    }
}

function err(...msg) { console.error(...msg); process.exit(1); }

function preload(list) {
    return list.reduce( (acc, cur) => {
	try {
	    acc[cur] = require(cur)
	} catch (e) {
	    err('preloading module failed:', e.message)
	}
	return acc
    }, {})
}

function puts(str) { process.stdout.write(String(str)); }

function evaluate(str, sandbox) {
    let vm = require('vm')
    vm.createContext(sandbox)
    return vm.runInContext(str, sandbox)
}

function irb(sandbox) {
    let repl = require('repl')
    console.error('Your document should be available via $')
    let r = repl.start('> ')
    Object.assign(r.context, sandbox)
}

main()
